const EventsList = [
    {
        id: 1,
        name: 'Android Study Jam: session 03',
        time: 'DEC 29, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-android-study-jam-session-03',
        tags: ['Android', 'Kotlin'],
        tagsText: 'Android Kotlin',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/event_banners/Kotlin-DSC-Promo-Event-Page-Thumbnail-R2-NAVY_Ek4Mp0g.png',
        shortDescription: 'Join us for the Workshop “Android Study Jam: session 03”🧑‍💻',
        description: `<h2>Greetings from GDSC GHRCE!</h2><p>We hope you all are doing great!</p><p>We are back with the third session of Android Study Jams!</p><p>In the first session, we covered the basic concepts in Kotlin. In the 2nd session, we did a quick introduction to the Android studio and made a simple birthday card application.</p><p>Now in the third session, we will learn some OOP concepts in Kotlin, And we will make a dice roller game in ANDROID STUDIO.</p><p>If you are new don't worry, it is a beginner-friendly workshop!</p><p>Join us for the Workshop<b> “Android Study Jam: session 03”</b>🧑‍💻</p><p><i><b>Date: 29th December'21</b></i></p><p><i><b>Time: 6 PM</b></i></p><p><i><b>Platform: YouTube</b></i></p><p>So, what are you waiting for?<b> RSVP</b> to attend the event!</p><p>Team GDSC GHRCE</p>`,
    },
    {
        id: 2,
        name: 'Session 2 - Android Study Jams!',
        time: 'DEC 10, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-session-2-android-study-jams/',
        tags: ['Android', 'Kotlin'],
        tagsText: 'Android Kotlin',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/event_banners/Kotlin-DSC-Promo-Event-Page-Thumbnail-R2-NAVY.png',
        shortDescription: 'Learn how to build Android apps in the Kotlin programming language, using the curriculum provided by Google.',
        description: `<h3><u><i><b>Android Study Jam📱</b></i></u></h3><p> GHRCE GDSC is back again with an exciting opportunity for all enthusiastic students to learn how to build Android apps in the Kotlin programming language, using the curriculum provided by Google.</p><p><b>Event Timeline:</b> <i>Nov 29, 2021 - Jan 10, 2022</i></p><p>👉🏻<b>What is Android study jams –</b></p><p>--&gt; This course is completely free.</p><p>--&gt; This course covers both beginner and intermediate topics on building Android apps in Kotlin. </p><p>--&gt; No programming experience is needed! Join us to advance your skills and learn how to build apps.</p><p>👉🏻<b>What's in it for you?</b></p><p>--&gt; Learn Android fundamentals Basics in building an android app with "ANDROID BASICS IN KOTLIN COURSE"</p><p>--&gt; Earn badges for google Developer's profile</p><p>--&gt; Get a certificate of completion</p><p>--&gt; Develop real-world Android Apps in team</p><p>--&gt; Stand a chance to feature your app by Google</p><p>👉🏻<b>Who can apply?</b></p><p>Anyone interested in learning android development can apply, No prior experience is required. You will learn everything from scratch through live sessions and hands-on practice.</p><p>👉🏻<b>How to proceed?</b></p><p><i><b>First, make your developers profile :</b></i></p><p><a href="https://google.dev/u/new"><span>https://google.dev/u/new</span></a>&nbsp;&nbsp;</p><p><b><i>RSVP to enroll!</i></b></p>`,
    },
    {
        id: 3,
        name: 'Wo(Men) In Tech: The beginning',
        time: 'DEC 9, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-women-in-tech-the-beginning/',
        tags: ['Career Development'],
        tagsText: 'Career Development',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/WIT_Registration%20%282%29_skON5zU.png',
        shortDescription:
            'Info Session of WO(MEN) IN TECH Day 1 - How Women Impact the tech Welcoming session addressing participant’s issues and impact of Women in Tech Day 2 - Insight on how the world is helping women to grow Talking about different opportunities like internships, scholarships, etc.',
        description: `<h2 style="text-align: center;">What is <b><i>WO(MEN) IN TECH</i></b> aka <b><i>(W(M)IT)</i></b>?</h2><p style="text-align: center;">The program Wo(Men) In Tech(WIT) focuses on the concept of helping women who are either doing Engineering or are pursuing a career in the Technical Field. The Women in Tech doesn’t only focus on the concept of Women helping Women but also focuses on Men helping Women. The program consists of a series of recurring events( known as BOT) on different topics addressing the issues related to women and how can they overcome them and Hackathons to give women the opportunity to express their thoughts, learn and Real Life situation experience where we can observe how Men and Women helping each other can create a balance between both genders and help each other grow in the coming future. Alas! we break the stereotype that behind every man there is a woman but vice-versa can happen too.</p><p style="text-align: center;"><i>The program’s opening ceremony is taking place on the <b>9th</b> and <b>10th</b> of <b>December</b> on the occasion of <b>Grace Hopper </b>and<b> Ada Lovelace</b> Birthdays.  </i></p><p style="text-align: center;"><b>DAY – 1:</b> <i>Welcoming session addressing participants' issues and what they expect.</i></p><p style="text-align: center;"><b>DAY – 2:</b> <i>Talking about different opportunities like internships, scholarships, etc.</i></p><p> </p><p style="text-align: center;"><b><i>What is Bringing Opportunities in Tech(BOT)</i></b></p><p style="text-align: center;">BOT will be a series of recurring sessions where several Accomplished speakers (CEOs, activists, research, working in good MNCs, specialized in different Tech Domains) will be interacting and giving us good insight with Girls in India who are finding it difficult to grow in the tech domain. Also, sessions can be any women program generic(internship program, scholarship program, any certified course) which can help them to know about different opportunities for Women.</p><p> </p><p style="text-align: center;">The Above program is Initiated and Organised by 15 GDSCs across the different states of India.&nbsp;</p><p style="text-align: center;"><b><i>RSVP now!</i></b></p>`,
    },
    {
        id: 4,
        name: 'Intro To Android Study Jams!',
        time: 'DEC 6, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-intro-to-android-study-jams/',
        tags: ['Android', 'Kotlin'],
        tagsText: 'Android Kotlin',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/event_banners/Kotlin-DSC-Promo-Event-Page-Thumbnail-R2-NAVY.png',
        shortDescription: 'Learn how to build Android apps in the Kotlin programming language, using the curriculum provided by Google.',
        description: `<h3><u><i><b>Android Study Jam📱</b></i></u></h3><p> GHRCE GDSC is back again with an exciting opportunity for all enthusiastic students to learn how to build Android apps in the Kotlin programming language, using the curriculum provided by Google.</p><p><b>Event Timeline:</b> <i>Nov 29, 2021 - Jan 10, 2022</i></p><p>👉🏻<b>What is Android study jams –</b></p><p>--&gt; This course is completely free.</p><p>--&gt; This course covers both beginner and intermediate topics on building Android apps in Kotlin. </p><p>--&gt; No programming experience is needed! Join us to advance your skills and learn how to build apps.</p><p>👉🏻<b>What's in it for you?</b></p><p>--&gt; Learn Android fundamentals Basics in building an android app with "ANDROID BASICS IN KOTLIN COURSE"</p><p>--&gt; Earn badges for google Developer's profile</p><p>--&gt; Get a certificate of completion</p><p>--&gt; Develop real-world Android Apps in team</p><p>--&gt; Stand a chance to feature your app by Google</p><p>👉🏻<b>Who can apply?</b></p><p>Anyone interested in learning android development can apply, No prior experience is required. You will learn everything from scratch through live sessions and hands-on practice.</p><p>👉🏻<b>How to proceed?</b></p><p><i><b>First, make your developers profile :</b></i></p><p><a href="https://google.dev/u/new"><span>https://google.dev/u/new</span></a>&nbsp;&nbsp;</p><p><b><i>RSVP to enroll!</i></b></p>`,
    },
    {
        id: 5,
        name: 'Google Play Academy Study Jam - Store Listing Workshop',
        time: 'NOV 26, 2021',
        url: 'Google Play Academy Study Jam - Store Listing Workshop',
        tags: ['Android', 'Career Development', 'Assistant', 'Actions on Google'],
        tagsText: 'Android Career Development Assistant Actions on Google',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/Instagram%20post%20-%2020.png',
        shortDescription:
            'In this workshop, we’ll discuss what to look for when you are writing your App description and selecting what graphics, videos, and screenshots to add to your store listing, as well as how running experiments in the Google Play Console can help you give real user data on how to improve your store listing.',
        description: `<h3 style="text-align: left;"><b><i>Store listing workshop</i></b></h3><p>Telling your brand story through your store listing can attract more users to download and install your app. Providing an engaging app description, feature video and graphics, and great screenshots in an easy and free way to communicate your brand story to potential users. In this workshop, we’ll discuss what to look for when you are writing your App description and selecting what graphics, videos, and screenshots to add to your store listing, as well as how running experiments in the Google Play Console can help you give real user data on how to improve your store listing.</p><p>Study Jams are simply community-run study groups for developers to grow and up-skill themselves.</p><p>Similarly, a Google Play Study Jam is a learning program combining practical developer experience with Google Play expertise.</p><p>Like-minded developers and practitioners come together to share and further their knowledge of Google Play through interactive classrooms and discussion.</p><p><b><i>Important:</i></b>&nbsp;</p><p>In order to complete the store listing workshop and receive the physical swag, you must complete both sub-topics of the store listing workshop.&nbsp;Registration is mandatory for a guaranteed spot in the study jam and tracking your progress throughout.</p><p>We will be kicking off the 1st phase i.e Store Listing Workshop this month for 2 days which goes from</p><ol><li><b>26th</b> <b>Nov 2021, 4 pm</b> (Store Listing Workshop - <b>Description</b>)</li><li><b>27th</b> <b>Nov 2021, 11 am</b> (Store Listing Workshop - <b>Preview Assets</b>)</li></ol><p>Sign up for study jam sessions using this link:&nbsp;<a href="http://bit.ly/gplaystudyjamnagpur"><span>bit.ly/gplaystudyjamnagpur</span></a>&nbsp;</p><p><b style="font-style: italic;">Don't forget to fill the post-event survey form </b>(will be provided during the session)<b style="font-style: italic;"> after attending both workshops to receive your Swags!</b></p>`,
    },
    {
        id: 6,
        name: 'CloudFest 2.0: Road to Google Cloud Certifications',
        time: 'OCT 28, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-cloudfest-20-road-to-google-cloud-certifications/',
        tags: ['Career Development', 'Google Cloud Platform'],
        tagsText: 'Career Development Google Cloud Platform',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/Instagram%20post%20-%2013_rsa6fx4.png',
        shortDescription: 'Why is it necessary to get Google Cloud Certified? Want to get Google Cloud Certified? Hear directly from Magda Jary [Global Lead, Google Cloud Certifications, and Digital Badges GTM]',
        description: `<p>📍93% of IT decision-makers around the world agree that certified employees provide added value above and beyond the cost of certification.</p><p>📍87% of Google Cloud certified individuals are more confident about their cloud skills.</p><p>📍More than 1 in 4 Google Cloud certified individuals took on more responsibilities or leadership roles in their respective domains.</p><p>Google Cloud certifications validate your expertise and showcase your ability to transform businesses with Google Cloud technology.</p><p>Join us for the event <b>CloudFest 2.0: Road to Google Cloud Certifications</b> with <b>GDSC GHRCE</b> that will take you to Google Cloud certification journey and will be helping you to begin your journey of becoming Google Cloud certified.</p><p>Discover all about Google Cloud Certifications and ask questions that you might have directly from our speaker:</p><p><b>Magda Jary</b></p><p>Global Lead, Google Cloud Certification &amp; digital badges GTM</p><p>📅 <b>Event date: 28th Oct 2021</b></p><p>🕑 <b>Time: 11 AM IST</b></p>`,
    },
    {
        id: 7,
        name: 'CloudFest 2.0: BigQuery + AutoML',
        time: 'OCT 16, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-cloudfest-20-bigquery-automl/',
        tags: ['Google Cloud Platform', 'AI', 'Machine Learning'],
        tagsText: 'Google Cloud Platform AI Machine Learning',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/Instagram%20post%20-%207.png',
        shortDescription: 'Get ready to dive into the world of Cloud, ML, and explore more about BigQuery and AutoML.',
        description: `<p>Do you know the power behind Google Search? </p><p>Have you ever used Google Photos and Google Lens?</p><p>Both are so fast that within a second it loads millions of results.</p><p><b>BigQuery</b> is a fully managed and serverless data warehouse solution available in the Google Cloud Platform that gives anyone the capability to analyze terabytes of data with built-in features like machine learning, geospatial analysis, and business intelligence in just a matter of seconds.</p><p><b>Cloud AutoML</b> is a suite of products enabling developers with limited ML expertise to build high-quality models using transfer learning and Neural Architecture Search techniques. </p><p>Get ready to dive into the world of Cloud, ML, and explore more about BigQuery and AutoML.</p><p>Join CloudFest 2.0: BigQuery + AutoML with GDSC GHRCE as this introductory session will help you in the 30 Days Of Google Cloud Program and also to those who would like to learn something new. </p><p>Discover more about BigQuery and AutoML with our speaker:</p><p><b>Rushabh Vasa</b></p><p>Co-founder, Agrahyah Technologies &amp; <a href="http://Aawaz.com"><span>Aawaz.com</span></a></p><p>Google Developers Expert - Cloud</p><p>Mentor, Google for Start-ups</p><p>📅 Event date: 16th Oct 2021</p><p>🕑 Time: 4:30 PM IST</p>`,
    },
    {
        id: 8,
        name: 'PULL REQUEST - An Open Source Workshop',
        time: 'OCT 2, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-pull-request-an-open-source-workshop/',
        tags: ['Open Source', 'Git', 'GitHub', 'Career Development'],
        tagsText: 'Open Source Git GitHub Career Development',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/Instagram%20post%20-%202.png',
        shortDescription: 'Get ready to dive deep into the ocean of Open Source and explore new opportunities with GDSC GHRCE!✨ Start your Open Source journey with us, learn how to make your first PR, explore initiatives like Hacktoberfest, GSoC, GSoD and so much more!',
        description: `<p><i>Firefox, Linux, Python, Tensorflow, </i>despite being tools for different domains, have one thing in common, These are all <b>"Open Source"</b>!<br></p><p>📍Want to get started with open-source? We have just the right meet-up planned for you!</p><p>Get ready to dive deep into the ocean of Open Source and explore new opportunities with<b> GDSC GHRCE!</b> ✨</p><p>As a beginner in the field of open source, it can be quite overwhelming to figure out where to begin? How to find a suitable project you can contribute to? and at last, How to get your code merged?</p><p>Join us on<b> </b><i><u><b>Pull Request</b> - An Open Source Workshop</u></i> to discover the open-source world and learn about various opportunities with&nbsp;</p><p><b>Soham Shah</b>, S<i>oftware Engineer, Mentor GSSOC'21 &amp; Ex- Quicko</i>,&nbsp;</p><p>and</p><p>- Start your Open Source journey</p><p>- Learn how to make your first PR</p><p>- Explore initiatives like <i><b>Hacktoberfest, GSoC, GSoD </b></i></p><p>and so much more!</p>`,
    },
    {
        id: 9,
        name: 'Investments for Students',
        time: 'SEP 26, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-investments-for-students/',
        tags: ['Career Development', 'Investing'],
        tagsText: 'Career Development Investing',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/FinFleeposter.png',
        shortDescription:
            '“You don’t need to be a rocket scientist. Investing is not a game where the guy with the 160 IQ beats the guy with 130 IQ.” -Warren Buffet 🚀 Join us 🎉 while we bust the greatest myths, and talk about why and how students can get started with investments, together, with Vedant Bahel (P.s. also a student!) on the 26th of September at 4 PM.',
        description: `<p>"How many millionaires do you know who have become wealthy by investing in savings accounts?" -Robert G Allen</p><p>As students who are about to/ have started earning, let us remind you, that a mere 100 rupees are often sufficient to get started with investing.🌟</p><p>“You don’t need to be a rocket scientist. Investing is not a game where the guy with the 160 IQ beats the guy with 130 IQ.”  -Warren Buffet 🚀</p><p>Join us 🎉 while we bust the greatest myths, and talk about why and how students can get started with investments, together, with Vedant Bahel (P.s. also a student!) on the 26th of September at 4 PM.</p>`,
    },
    {
        id: 10,
        name: 'GDSC GHRCE REBOOT',
        time: 'SEP 12, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-gdsc-ghrce-reboot/',
        tags: ['Career Development', 'Flutter', 'Google Cloud Platform', 'AI', 'Machine Learning'],
        tagsText: 'Career Development Flutter Google Cloud Platform AI Machine Learning',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/Untitled-2-01_BRp82AB.png',
        shortDescription: "Google Developer Student Clubs – GHRCE Nagpur has been re-established on our campus. Join us for GDSC GHRCE REBOOT, as we unveil what's new in our club!",
        description: `<p>Are you looking for a new experience?</p><p>Do you want to have fun, learn and develop your skills?</p><p>Google Developer Student Clubs – GHRCE Nagpur has been re-established on our campus. Join us for GDSC GHRCE REBOOT, as we unveil what's new in our club!</p><p>👉 Learn more about the Google Developer Student Club.</p><p>👉 Know more about the upcoming events.</p><p>👉 Meet our core team.</p><p>👉  Ask us your burning questions.</p><p>Tune in to YouTube, today at 5 pm for Info Session, Tech Talks, AMA, and more.</p><p>Don't forget to stick around till the end because you might not want to miss out on the Ask me Anything session with our panelists.</p><p>👉 Event link: <a href="https://www.youtube.com/watch?v=4_JwZ3Mn__4"><span>https://www.youtube.com/watch?v=4_JwZ3Mn__4</span></a>&nbsp;</p><p>👉  Sunday, September 12th, 2021 5:00 PM</p><p>Regards,</p><p>Team GDSC GHRCE</p>`,
    },
    {
        id: 11,
        name: 'Crack with DSC GHRCE (May Week 3)',
        time: 'MAY 23, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-crack-with-dsc-ghrce-may-week-3/',
        tags: ['Career Development', 'CP'],
        tagsText: 'Career Development CP',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/EventThumbnail1.png',
        shortDescription: '',
        description: `<p>Crack With GDSC GHRCE is a weekly quiz organized by GDSC GHRCE with a motive to promote and enhance Competitive Coding skills and knowledge of concepts like Data Structures and Algorithms among students. </p><p>Knowing a programming language isn't enough. What's more important is Logic building and Problem-solving. Therefore, we present you the opportunity to participate in our weekly contest 'Crack with GDSC GHRCE' where you'll get to solve a new problem every week.</p><p>Here's the flow:</p><p>1. Fill the Google form for registering.</p><p>Link: <a href="https://forms.gle/Ju59YHyuLh2VxwDs5"><span>https://forms.gle/Ju59YHyuLh2VxwDs5</span></a></p><p>2. Join the GDSC GHRCE Classroom (only once)</p><p>Link: <a href="https://onlinegdb.com/classroom/invite/rkOwBT9DP"><span>https://onlinegdb.com/classroom/invite/rkOwBT9DP</span></a></p><p>3. Get a new Question Every Monday at 7 PM.</p><p>4. Submit in any 1 language till Saturday, 8 PM.</p><p>5. Get results at 8 PM, every Sunday.</p><p>Bonus: Every month, a winner in 4 consecutive weeks shall be entitled as the 'Coder of the Month' and will be eligible for exclusive goodies.</p>`,
    },
    {
        id: 12,
        name: 'Crack with GDSC GHRCE',
        time: 'MAY 9, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-crack-with-gdsc-ghrce/',
        tags: ['Career Development', 'CP'],
        tagsText: 'Career Development CP',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/icon_evi8PUV.png',
        shortDescription: '',
        description: `<p>Crack With GDSC GHRCE is a weekly quiz organized by GDSC GHRCE with a motive to promote and enhance Competitive Coding skills and knowledge of concepts like Data Structures and Algorithms among students.&nbsp;</p><p>Knowing a programming language isn't enough. What's more important is Logic building and Problem-solving. Therefore, we present you the opportunity to participate in our weekly contest 'Crack with GDSC GHRCE' where you'll get to solve a new problem every week.</p><p>Here's the flow:</p><p>1. Fill the Google form for registering.</p><p>     Link: <a href="https://forms.gle/Ju59YHyuLh2VxwDs5"><span>https://forms.gle/Ju59YHyuLh2VxwDs5</span></a></p><p>2. Join the GDSC GHRCE Classroom (only once)</p><p>     Link: <a href="https://onlinegdb.com/classroom/invite/rkOwBT9DP"><span>https://onlinegdb.com/classroom/invite/rkOwBT9DP</span></a></p><p>3. Get a new Question Every Monday at 7 PM.</p><p>4. Submit in any 1 language till Saturday, 8 PM.</p><p>5. Get results at 8 PM, every Sunday.</p><p>Bonus: Every month, a winner in 4 consecutive weeks shall be entitled as the 'Coder of the Month' and will be eligible for exclusive goodies.</p>`,
    },
    {
        id: 13,
        name: "Let's Learn Design",
        time: 'MAR 20, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-lets-learn-design/',
        tags: ['UI / UX'],
        tagsText: 'UI / UX',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/Untitled-4-01.png',
        shortDescription: '',
        description: `<p>After the much loved UI/UX Hands-on Workshop, DSC GHRCE is back with another interesting Hands-on session 'Let's learn design' with Saurabh Joshi. Saurabh is an Application Development Associate at Accenture and a professional graphic designer.👨🏻‍💻<br></p><p>Join us this Saturday, 20th March at 4PM on YouTube. Let's make this weekend a productive one!🎯</p><p>Register here: <a href="http://bit.ly/LetsLearnDesign"><span>http://bit.ly/LetsLearnDesign</span></a></p><p>Pre-requisite Software - Adobe Photoshop</p>`,
    },
    {
        id: 14,
        name: 'UI/UX Design Hands On Workshop',
        time: 'JAN 23, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-uiux-design-hands-on-workshop/',
        tags: ['UI / UX'],
        tagsText: 'UI / UX',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/Untitled-1_fov3G7U.png',
        shortDescription: '',
        description: `<p>Looking to upgrade your skills this new year? Well, UI/UX is one of the most popular skills people are looking to learn in 2021. </p><p>You’ve guessed it!</p><p>DSC GHRCE is here with its new event “UI/UX Design Hands-on Workshop”. Learn the best practices of UI/UX Design and get Hands-on experience with our speaker Mr. Vaibhav Pathak, UI/UX Designer and Application Development Associate at Accenture.</p><p>Date: 23rd Jan 2021</p><p>Time: 4:00PM</p><p>Venue: Live Stream on YouTube</p><p>Register here at - <a href="http://bit.ly/uiuxdscghrce"><span>http://bit.ly/uiuxdscghrce</span></a></p>`,
    },
    {
        id: 15,
        name: 'Arrays and Bit Manipulation',
        time: 'JAN 8, 2021',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-arrays-and-bit-manipulation/',
        tags: ['Programming', 'Arrays', 'Bit Manipulation', 'Career Development'],
        tagsText: 'Programming Arrays Bit Manipulation Career Development',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/TCC_1_Uf0Ck3k.png',
        shortDescription: 'Learn Something new today...',
        description: `<p>Are you someone who struggles with time complexity of various searching and sorting? </p><p>Do you know you can use bit manipulation to not just simplify but fasten your code as well?</p><p>Arrays are one of the basic data structures out there and its thorough understanding is a must.</p><p>Well, what about bit manipulation? Do you know it can help you do a lot of mathematical tricks which can help you reduce time complexity of your code.</p><p>If not, worry not for The Coding Culture has got you covered.</p><p>Arrays and Bit Manipulation are topics which can be a bit tricky in Competitive Programming. </p><p>To get a clearer idea of these, we are back with a webinar on 8th and 9th January from 5:00 PM onwards.</p><p>Join The Coding Culture here-</p><p><a href="https://linktr.ee/thecodingculture"><span>https://linktr.ee/thecodingculture</span></a></p>`,
    },
    {
        id: 16,
        name: 'REINFORCEMENT LEARNING: PLAYING TO WIN',
        time: 'DEC 19, 2020',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-reinforcement-learning-playing-to-win/',
        tags: ['AI', 'Machine Learning'],
        tagsText: 'AI Machine Learning',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/RL%20With%20Shweta%20Bhatt.png',
        shortDescription: '',
        description: `<p>🏆Reign the ML world with Reinforcement Learning just like AlphaGo did by defeating the former Go champion Sedol.🥇<br></p><p>One of the things about reinforcement learning is that it tends to require exploration. We are here to provide just that!💡</p><p>💻Get Hands-On Experience and more with our amazing speaker🎤 Shweta Bhatt, Google Developer Expert for ML, and Data Scientist at Jupiter.</p><p>📢Join us live on <span><a href="https://youtu.be/ZTNYrkLzZ1Y">https://youtu.be/ZTNYrkLzZ1Y</a></span>&nbsp;YouTube on 19th Dec 2020, at 4 pm. Register here: <a href="http://bit.ly/3qIel5R" style="background-color: rgb(255, 255, 255);">bit.ly/3qIel5R</a></p>`,
    },
    {
        id: 17,
        name: "DSC WOW | INDIA'S BIGGEST COLLABORATION",
        time: 'DEC 7, 2020',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-dsc-wow-indias-biggest-collaboration-prizes-worth-10-lakhs/',
        tags: ['Android', 'Web', 'AI', 'Machine Learning', 'AR / VR', 'UI / UX'],
        tagsText: 'Android Web AI Machine Learning AR / VR UI / UX',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/favicon_RIu8jMC.png',
        shortDescription: '',
        description: `<p>DSC WOW is finally here!</p><p>We cannot be more excited to invite you all to be a part of this 7 Day technological celebration, hosted by more than 120 DSC chapters across India. DSC WOW is a week-long virtual event consisting of webinars &amp; workshops for five days and the ‘CodeOffDuty’ Hackathon for the last 48 hours.</p><p>DSC WOW will bring Industry leaders as mentors and college students from all over the country and beyond to compete over 48 hours to develop creative solutions to real-world problems. There are multiple prizes and swags to be won!</p><p>Join us to learn in domains like AI/ML, Blockchain, Design Thinking from Googlers, and experts from all over the world! We have Miri Rodriguez, Ada Rose Cannon, Rachel Hue, and Mrinal Jain to name a few, as speakers lined up to give you insights like never before.</p><p>Use the links below for registration:</p><p>Register here <span><a href="http://dscwow.tech">http://dscwow.tech</a></span>&nbsp;for 'Workshops'</p><p>Register here <a href="https://hackathon.dscwow.tech/"><span>https://hackathon.dscwow.tech/</span></a>  for ‘CodeoffDuty’ Hackathon,</p>`,
    },
    {
        id: 18,
        name: 'Number Theory and Mathematics',
        time: 'DEC 5, 2020',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-number-theory-and-mathematics/',
        tags: ['Career Development'],
        tagsText: 'Career Development',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/Thumbnail%20-%20TCC%20Webinar_5lmuE8x.png',
        shortDescription: '',
        description: `<p>“Dive deep enough into anything, and you’ll find mathematics.”</p><p>As you know that mathematics is important in competitive programming but there may be confusion about where to start and how much to learn? Don't worry because we at The Coding Culture are here with our first webinar about Number Theory and Mathematics which will give you a better understanding of these topics and a great start towards the Competitive Programming World.</p><p>The best part is we will be taking care of all your doubts too so make yourself available from 5.00 P.M. Onwards on the 4th, 5th, and 6th of December</p><p>This is a part of the webinar series which will cover all the topics that are required to be in this Competitive Programming world.</p>`,
    },
    {
        id: 19,
        name: 'Get it Done with the Experts',
        time: 'NOV 14, 2020',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-get-it-done-with-the-experts/',
        tags: ['Career Development'],
        tagsText: 'Career Development',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/banner-sqaure_KKqUuTn.png',
        shortDescription: '',
        description: `<p>Competitive Programming is quite the buzzword these days, and for a good reason. The main objective of Competitive Programming is to encourage problem-solving logically and mathematically, which is an incredibly desirable skill in programmers.</p><p>Getting into it though can be intimidating, especially as a beginner.</p><p> </p><p>If you are someone who is struggling with how to start Competitive Coding or even if someone who has started with it but lost the way ahead, this is just what you need. </p><p> </p><p>💡 The Coding Culture, an initiative by 50+ DSC all across India, brings to you a webinar on "Get it done with the experts". Get ready to know how to kick-start your journey in the world of Competitive Programming! 💡</p><p>The webinar is going to be on best practices, learning resources, and much more.</p><p> </p><p>📍📍</p><p>The webinar is going to be a panel discussion with </p><p><b>Aanshul Sadaria</b></p><p>Software Engineer II at Google; Institute Gold Medalist; Patent Holder (Internship at Adobe)</p><p> </p><p><b>Kunal Kushwaha</b></p><p>CNCF Intern | Co-Founder at Code for Cause | MLH Fellowship Team Leader | GSoC Mentor</p><p> </p><p><b>Aarnav Jindal</b></p><p>Google Kickstart top 3 percentile | CodeChef 6 star | CodeForces 1932 | SDE Cure.Fit</p>`,
    },
    {
        id: 20,
        name: 'Cloud Fest - Introduction to Cloud Computing',
        time: 'OCT 10, 2020',
        url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-presents-cloud-fest-introduction-to-cloud-computing/',
        tags: ['Google Cloud Platform'],
        tagsText: 'Google Cloud Platform',
        artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_175,q_auto:good,w_175/v1/gcs/platform-data-dsc/events/thumbnail6-01_6sx3NL4.png',
        shortDescription: '',
        description: `<p>Usage of Cloud Infrastructure has been increasing day by day, considering the pandemic situation we are in, cloud services have been the backbone of our Educational, Business, and WFH requirements. In order to get to know these concepts well, we have come up with a session on "Introduction to Cloud" in our first session of the CloudFest series.&nbsp;&nbsp;</p><p><br></p><p>Date - 10/10/2020</p><p>Time - 10:00AM</p><p>Event Link -&nbsp;<a href="http://tiny.cc/dsccloudfest">http://tiny.cc/dsccloudfest</a></p><p>Excited?&nbsp; Spread the word, share your experiences, and tag @dscghrce on <a href="https://www.instagram.com/dscghrce/">Instagram</a> &amp; <a href="http://twitter.com/dscghrce">Twitter</a>.</p>`,
    },
    // {
    //     id: 0,
    //     name: '',
    //     time: '',
    //     url: '',
    //     tags: [],
    //     artwork: '',
    //     shortDescription: '',
    //     description: ``,
    // },
]

export default EventsList

export const CurrentEvent = {
    id: 21,
    name: 'The Flutterverse - Hot reload the Flutter master version of yourself!',
    time: 'Dec 15, 2021 - Jan 22, 2022, 6:00 PM (IST)',
    url: 'https://gdsc.community.dev/events/details/developer-student-clubs-gh-raisoni-college-of-engineering-nagpur-presents-the-flutterverse-hot-reload-the-flutter-master-version-of-yourself/',
    tags: ['Career Development', 'Flutter'],
    tagsText: 'Career Development Flutter',
    artwork: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_3,f_auto,g_center,h_150,q_auto:good,w_150/v1/gcs/platform-data-dsc/events/Frame%208_b14B0Ca.png',
    shortDescription: '“The Flutterverse” is a 4-week Flutter Bootcamp followed by a Mobile app Development Hackathon.',
    description: `<h3><b>The Flutterverse&nbsp;</b></h3><p><b>Hot reload the Flutter master version of yourself!</b></p><p>Flutter has emerged as a versatile software development kit (SDK) that empowers developers worldwide to create intuitive applications for Android, Linux, iOS, Windows, and the web from a single codebase. You can say that it's<i> 3 Platforms, 1 Code solution! </i></p><p>No wonder, more than 500,000 developers use Flutter every month. With more than 2 million users, today Flutter has also become one of the most popular app development kits.</p><p>With Flutterverse, start your flutter development journey! </p><p><i>Join us for this 4-week Flutter Bootcamp followed by a Mobile development hackathon! </i></p><p><b><u>What is Flutterverse about? </u></b></p><p>“The Flutterverse” is a 4-week Flutter Bootcamp followed by a mobile app development hackathon.</p><ul><li>The course is beginner-friendly and will be taught by our amazing Flutter Developers!&nbsp;</li><li>The syllabus is divided into a 4-week curriculum. (curriculum shared below )</li><li>Each week the decided syllabus will be taught along with Live QnA support from Monday to Friday. On Fridays, we will conduct a Hands-on Project building Workshop based on the content taught in that respective week.</li><li>There will be a total of 4 Project workshops, all the participants will be required to submit their customized versions of the project on the GitHub Repository of The Flutterverse individually by Monday 11:59 pm of the following week.</li><li>The progress will also be tracked through a leaderboard made by us, there will be no disqualification based on submissions but it will affect the eligibility to become a winner and be eligible for goodies.</li><li>In Week 5 we will provide a list of Problem Statements to the participants for the Final Project/ Hackathon. This Project will be individual, everyone will get 4 days (96 Hrs) to build their projects.</li><li>The submissions of the Final Project will also be on GitHub, the same way as the weekly Projects.</li><li>On the Saturday of Week 5, the winner and 5 Top Performers will be announced and rewarded.</li><li><a href="https://elegant-droplet-c7d.notion.site/Flutter-Bootcamp-bdfb68e0313449ae888b36c545f8deaa"><u>Syllabus</u></a></li></ul><p>So what are you waiting for?</p><p><b><i>RSVP now and stand a chance to get Paid Internship Support from GDSC GHRCE and some Lucky participants will receive swags and goodies too!</i></b></p>`,
}
