import {AiOutlineMail, AiFillDropboxCircle, AiFillCodepenCircle} from 'react-icons/ai'
import {BsGithub, BsInstagram, BsFacebook, BsYoutube, BsWhatsapp, BsTelegram, BsTwitter, BsLinkedin, BsMedium, BsReddit, BsDiscord, BsPinterest, BsTwitch, BsDribbble, BsBehance, BsStackOverflow, BsSpotify, BsVimeo} from 'react-icons/bs'
import {CgWebsite} from 'react-icons/cg'
import {FaDev, FaQuora, FaTumblrSquare, FaItchIo} from 'react-icons/fa'
import {IoLogoGooglePlaystore} from 'react-icons/io5'

export const SocialPlatformsIconsData = [
    {
        id: 1,
        Icon: BsGithub,
        name: 'GitHub',
        tag: 'github',
        color: '#171515',
    },
    {
        id: 2,
        Icon: BsInstagram,
        name: 'Instagram',
        tag: 'instagram',
        color: '#fb3958',
    },
    {
        id: 3,
        Icon: BsFacebook,
        name: 'Facebook',
        tag: 'facebook',
        color: '#4267B2',
    },
    {
        id: 4,
        Icon: BsYoutube,
        name: 'YouTube',
        tag: 'youtube',
        color: '#c4302b',
    },
    {
        id: 5,
        Icon: BsWhatsapp,
        name: 'WhatsApp',
        tag: 'whatsapp',
        color: '#25D366',
    },
    {
        id: 6,
        Icon: BsTelegram,
        name: 'Telegram',
        tag: 'telegram',
        color: '#0088CC',
    },
    {
        id: 7,
        Icon: BsTwitter,
        name: 'Twitter',
        tag: 'twitter',
        color: '#1da1f2',
    },
    {
        id: 8,
        Icon: BsLinkedin,
        name: 'LinkedIn',
        tag: 'linkedIn',
        color: '#0a66c2',
    },
    {
        id: 9,
        Icon: BsMedium,
        name: 'Medium',
        tag: 'medium',
        color: '#000000',
    },
    {
        id: 10,
        Icon: BsReddit,
        name: 'Reddit',
        tag: 'reddit',
        color: '#F74300',
    },
    {
        id: 11,
        Icon: BsDiscord,
        name: 'Discord',
        tag: 'discord',
        color: '#738adb',
    },
    {
        id: 12,
        Icon: BsPinterest,
        name: 'Pinterest',
        tag: 'pinterest',
        color: '#DA0021',
    },
    {
        id: 13,
        Icon: CgWebsite,
        name: 'Website',
        tag: 'website',
        color: '#0F60b6',
    },
    {
        id: 14,
        Icon: FaDev,
        name: 'Dev Platform',
        tag: 'dev_platform',
        color: '#000000',
    },
    {
        id: 15,
        Icon: FaQuora,
        name: 'Quora',
        tag: 'quora',
        color: '#B02925',
    },
    {
        id: 16,
        Icon: BsTwitch,
        name: 'Twitch',
        tag: 'twitch',
        color: '#5F3E9D',
    },
    {
        id: 17,
        Icon: AiOutlineMail,
        name: 'Email',
        tag: 'email',
        color: '#ffffff',
    },
    {
        id: 18,
        Icon: BsDribbble,
        name: 'Dribble',
        tag: 'dribble',
        color: '#E24178',
    },
    {
        id: 19,
        Icon: BsBehance,
        name: 'Behance',
        tag: 'behance',
        color: '#2B6DD1',
    },
    {
        id: 20,
        Icon: IoLogoGooglePlaystore,
        name: 'Play Store',
        tag: 'play_store',
        color: '#F0BE00',
    },
    {
        id: 21,
        Icon: FaTumblrSquare,
        name: 'Tumblr',
        tag: 'tumblr',
        color: '#EC0000',
    },
    {
        id: 22,
        Icon: AiFillDropboxCircle,
        name: 'Dropbox',
        tag: 'dropbox',
        color: '#0C227A',
    },
    {
        id: 23,
        Icon: AiFillCodepenCircle,
        name: 'Codepen',
        tag: 'codepen',
        color: '#000000',
    },
    {
        id: 24,
        Icon: FaItchIo,
        name: 'Itch.io',
        tag: 'itch.io',
        color: '#F25756',
    },
    {
        id: 25,
        Icon: BsStackOverflow,
        name: 'Stack Overflow',
        tag: 'stackoverflow',
        color: '#E77A24',
    },
    {
        id: 26,
        Icon: BsSpotify,
        name: 'Spotify',
        tag: 'spotify',
        color: '#1CCD5B',
    },
    {
        id: 27,
        Icon: BsVimeo,
        name: 'Vimeo',
        tag: 'vimeo',
        color: '#01A4E2',
    },
]
