const TeamMembers = [
    {
        name: 'Khushboo Agnihotri',
        role: 'GDSC Lead',
        profile: 'https://gdsc.community.dev/u/mm2gyj/',
        twitter: 'https://twitter.com/_Khushboo_21',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/khushboo_agnihotri_tnZ8u5n.jpeg',
    },
    {
        name: 'Aniket Singh',
        role: 'Technical Head',
        profile: 'https://gdsc.community.dev/u/mrtcwu/',
        twitter: 'https://twitter.com/aniketsiingh',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/aniket_singh_yUCwxqL.png',
    },
    {
        name: 'NEENAD SAHASRABUDDHE',
        role: 'Public Relations Head',
        profile: 'https://gdsc.community.dev/u/mcur27/',
        twitter: 'https://twitter.com/nenu4142',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/neenad_sahasrabuddhe_7ixCyoS.png',
    },
    {
        name: 'Aaliya Ali',
        role: 'Management Head',
        profile: 'https://gdsc.community.dev/u/m9azy6/',
        twitter: 'https://twitter.com/AaliyaAli_01',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/aaliya_ali_ZSRi28h.png',
    },
    {
        name: 'Shivam Kumar',
        role: 'Operations Head',
        profile: 'https://gdsc.community.dev/u/mjq4s8/',
        twitter: 'https://twitter.com/shivam_aiml',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/shivam_kumar_dmPclVA.png',
    },
    {
        name: 'Laksh Samdariya',
        role: 'Executive Team',
        profile: 'https://gdsc.community.dev/u/m6kr9n/',
        twitter: '',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/laksh_samdariya_uCzjpQN.jpg',
    },
    {
        name: 'Sobhan Bera',
        role: 'Executive Team',
        profile: 'https://gdsc.community.dev/u/sobhan/',
        twitter: 'https://twitter.com/berasobhan',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/sobhan_bera_ASJaCFd.png',
    },
    {
        name: 'Vidhanshu Borade',
        role: 'Executive Team',
        profile: 'https://gdsc.community.dev/u/vidhanshu/',
        twitter: '',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/vidhanshu_borade_5hzTEMI.png',
    },
    {
        name: 'Vidit Chawda',
        role: 'Executive Team',
        profile: 'https://gdsc.community.dev/u/mgjq3s/',
        twitter: '',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/vidit_chawda_xF1lkmH.png',
    },
    {
        name: 'Roshan Paturkar',
        role: 'Advisory Team',
        profile: 'https://gdsc.community.dev/u/m8ur2w/',
        twitter: 'https://twitter.com/roshan_paturkar',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/roshan_paturkar_HLmKFbh.png',
    },
    {
        name: 'AYON MOITRA',
        role: 'Advisory Team',
        profile: 'https://gdsc.community.dev/u/m6rrz9/',
        twitter: 'https://twitter.com/moitra_ayon',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/ayon_moitra_EaN2T8C.jpg',
    },
    {
        name: 'Vaibhav Pathak',
        role: 'Advisory Team',
        profile: 'https://gdsc.community.dev/u/m84wqg/',
        twitter: 'https://twitter.com/vaibhav_rpathak',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/vaibhav_pathak_ALg8niN.png',
    },
    {
        name: 'Shreyas Malewar',
        role: 'Advisory Team',
        profile: 'https://gdsc.community.dev/u/mjxwq4/',
        twitter: 'https://twitter.com/ShreyasMalewar',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/shreyas_malewar_1Rf52Ga.png',
    },
    {
        name: 'Rohit ranjan',
        role: 'Community Coordinator',
        profile: 'https://gdsc.community.dev/u/mbcffk/',
        twitter: 'https://twitter.com/Rohitra2020',
        image: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_250,q_auto:good,w_250/v1/gcs/platform-data-dsc/avatars/rohit_ranjan_zHSRDju.jpg',
    },
]

export default TeamMembers
